cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v11.11.0/bin/
  - pwd
  - npm i

stages:
  - deployTest

deployDevBackend3Test:
  stage: deployTest
  only:
    refs:
      - cicd
  script:
    - npm run build
    - rsync -a -e "ssh -p 22" . deploy@192.168.88.133:/opt/backend/rtalunchapp
    - ssh -p 22 deploy@192.168.88.133 "/nfs/san03/deploy/scripts/pm2lunch4rta.sh"
